AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample Lambda Function in Typescript
Globals:
  Function:
    Timeout: 3

Resources:
  TypescriptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/built
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        Typescript:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TypescriptApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TypescriptFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TypescriptFunction.Arn
  TypescriptFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TypescriptFunctionIamRole.Arn
